[package]
name = "WordProblemCLI"
version = "0.1.0"
edition = "2024"

[dependencies]
mongodb = "3.3.0"
rand = "0.10.0-rc.0"
tokio = { version = "1.47.1", features = ["rt", "rt-multi-thread", "macros"] }
